### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by yungcemic**

### CODE REVIEW

**Comment by vtfg** [comment]
Why you closed? Was a big cleanup in my code, i really enjoyed that..

**Comment by yungcemic** [comment]
I closed it because I did not test it and made a mistake, and I turn it back on so I will re-open pr when I test it. I don't have much free time. (Mistake is to loop all players but clearing chat of sender lol)

**Comment by yungcemic** [comment]
And I can't open it like this because I deleted the fork :/

**Comment by vtfg** [comment]
When I made the ClearChat command I searched about cleaning chat in Bukkit API, i found only this "solution". I will continue this project and make all fixes that you made. :+1:

**Pull request closed without merging**
